services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: sveltekit_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firebits_course
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - sveltekit_network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: sveltekit_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - sveltekit_network

volumes:
  mysql_data:

networks:
  sveltekit_network:
    driver: bridge
